return {
  TelescopeResultsTitle = { fg = C.black_1, bg = C.black_1 },
  TelescopePromptTitle = { fg = C.red, bg = C.red },
  TelescopePreviewTitle = { fg = C.black_1, bg = C.green },
  TelescopeResultsBorder = { fg = C.black_1, bg = C.black_1},
  TelescopePromptBorder = { fg = C.bg_1, bg = C.bg_1 },
  TelescopePreviewBorder = { fg = C.black_1M, bg = C.black_1},
  TelescopeSelectionCaret = { fg = C.red },
  TelescopeMatching = { fg = C.yellow },
  TelescopeSelection = { bg = C.grey_5 },
  TelescopeMultiSelection = { fg = C.blue },
  TelescopeMultiIcon = { fg = C.blue },
  TelescopeNormal = { bg = C.black_1 },
  TelescopePreviewNormal = { bg = C.black_1 },
  TelescopePromptNormal = { fg = C.fg, bg = C.bg_1 },
  TelescopeResultsNormal = { fg = C.black_1 },
  TelescopeBorder = { fg = C.bg_1, bg = C.black_1 },
  TelescopeTitle = { fg = C.fg },
  TelescopePromptCounter = { fg = C.grey_1 },
  TelescopePromptPrefix = { fg = C.red, bg = C.bg_1 },
  TelescopePreviewLine = { bg = C.grey_5 },
  TelescopePreviewMatch = { fg = C.yellow },
  TelescopePreviewPipe = { fg = C.yellow },
  TelescopePreviewCharDev = { fg = C.yellow },
  TelescopePreviewDirectory = { fg = C.blue },
  TelescopePreviewBlock = { fg = C.yellow },
  TelescopePreviewLink = { fg = C.blue },
  TelescopePreviewSocket = { fg = C.purple },
  TelescopePreviewRead = { fg = C.yellow },
  TelescopePreviewWrite = { fg = C.purple },
  TelescopePreviewExecute = { fg = C.green },
  TelescopePreviewHyphen = { fg = C.grey_1 },
  TelescopePreviewSticky = { fg = C.blue },
  TelescopePreviewSize = { fg = C.green },
  TelescopePreviewUser = { fg = C.yellow },
  TelescopePreviewGroup = { fg = C.yellow },
  TelescopePreviewDate = { fg = C.blue },
  TelescopePreviewMessage = { fg = C.fg },
  TelescopePreviewMessageFillchar = { fg = C.fg },
  TelescopeResultsClass = { fg = C.yellow },
  TelescopeResultsConstant = { fg = C.yellow },
  TelescopeResultsField = { fg = C.red },
  TelescopeResultsFunction = { fg = C.blue },
  TelescopeResultsMethod = { fg = C.blue },
  TelescopeResultsOperator = { fg = C.cyan },
  TelescopeResultsStruct = { fg = C.purple },
  TelescopeResultsVariable = { fg = C.red },
  TelescopeResultsLineNr = { fg = C.grey_1 },
  TelescopeResultsIdentifier = { fg = C.blue },
  TelescopeResultsNumber = { fg = C.orange },
  TelescopeResultsComment = { fg = C.grey_2 },
  TelescopeResultsSpecialComment = { fg = C.grey },
  TelescopeResultsDiffChange = { fg = C.none, bg = C.yellow },
  TelescopeResultsDiffAdd = { fg = C.none, bg = C.green },
  TelescopeResultsDiffDelete = { fg = C.none, bg = C.red },
  TelescopeResultsDiffUntracked = { fg = C.none, bg = C.grey_1 }
}
