prSections:
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  issues: []
  prs: []
repoPaths: {}
pager:
  diff: delta
showAuthorIcons: true
smartFilteringAtLaunch: true

ui:
  sectionsShowCount: true
table:
  showSeparators: true
  compact: false
colors:
  text:
    primary: "#cdd6f4"
    secondary: "#bac2de"
    inverted: "#1e1e2e"
    faint: "#6c7086"
    warning: "#fab387"
    success: "#a6e3a1"
    actor: "#bac2de"
  background:
    selected: "#45475a"
  border:
    primary: "#585b70"
    secondary: "#7f849c"
    faint: "#313244"
  inline:
    icons:
      newcontributor: "080"
      contributor: "075"
      collaborator: "141"
      member: "069"
      owner: "220"
      unknownrole: "244"
icons:
  inline:
    newcontributor: "󰎔"
    contributor: ""
    collaborator: ""
    member: ""
    owner: ""
    unknownrole: "󰭙"
